#!/bin/bash
#
# the script is for development purposes and used to test abt & docker images build
#
set -e

function test {
  OS=$1
  PKG=$2
  Docker/abt.docker sergevs42/$OS-abt -v 3.1.0 -b local -A "abts `pwd`" abts
  cp ~/repos/$PKG Docker/$OS
  docker build Docker/$OS/ -f Docker/$OS/Dockerfile.pre -t sergevs42/$OS-abt
}

test centos6.x86_64 el6/RPMS.test/abt-3.1.0-ssv1.el6.noarch.rpm
test centos7.x86_64 el7/RPMS.test/abt-3.1.0-ssv1.el7.noarch.rpm

test debian7.amd64 test/abt_3.1.0_all.deb
test debian8.amd64 test/abt_3.1.0_all.deb
test debian9.amd64 test/abt_3.1.0_all.deb

find Docker -type f -and \( -name '*.rpm' -or -name '*.deb' \) -delete
